### PR TITLE
Added checks

### PR DESCRIPTION
**Pull request by vysec**
Added checks for closed buckets but you can still list even though you can't find the size.

### CODE REVIEW

**Comment by sa7mon** [comment]
@vysec Thanks for the PR, can you recall which bucket name you were scanning when testing this?

**Comment by vysec** [comment]
1904

**Comment by vysec** [comment]
This takes into the edge case where you can’t list size or get a 403. But you can still list contents.

**Comment by sa7mon** [comment]
Does scanning with that bucket name give you an error? When I run with 3.6, I get back that it's found and closed which seems correct.

I'm not quite sure what functionality this code is adding.

**Comment by vysec** [comment]
The bucket is open to authenticated AWS users. Hence why I wrote this to find more buckets.

**Comment by vysec** [comment]
Adding bucket listings in here. Not sure why Travis cares but ok.

**Comment by vysec** [comment]
Re your prev question
image

**Comment by sa7mon** [comment]
Thanks for the contributions, and filling in the blanks here. Just a couple of quick things:

- Does your branch run in Python 3.6.4 for you? Because when I run it with the 1904 bucket in my buckets file, I get the following:

	```bash
	> python ./s3scanner.py sites.txt
	Traceback (most recent call last):
	  File "./s3scanner.py", line 108, in <module>
	    result = s3.checkBucket(bucket, result[1])
	  File "/Projects/s3scanner-vysec/s3utils.py", line 33, in checkBucket
	    if not "An error occured (" in output:
	TypeError: a bytes-like object is required, not 'str'
	```
   Looks like on line 33, you may need to wrap output in a str() call. I'm not sure if the substring check will still work on a bytes-like object that's been converted to a string, but probably. 

- I've switched the target branch for the merge to be the `enchancements` branch. This is sort of the sandbox where changes go to be tested before merging into `master`.

- In the future, I'm probably going to switch the bucket classifications from found-open/found-closed/not-found to be more verbose. Maybe like 'readable-writeable/readable-not-writeable'. Nevertheless, I think I'd like to keep the current classifying of listable, but not syncable buckets as '[found] [closed]'. Could you change it so that 403 buckets are classified as '[found] [closed]'? But still list the contents if the --list argument is supplied.

Again, thanks for the contributions. I had the `list bucket contents` item on the roadmap as the next big feature to tackle.

**Comment by sa7mon** [comment]
Oh also the Travis test is failing because the signature changed when you added the `--list` argument. To get the tests passing again, just change line 22 of `test_scanner.py` from:
```python
assert "usage: s3scanner [-h] [-o OUTFILE] [-c] [-r] [-d] buckets" in e.stdout.decode('utf-8')
```
to:
```python
assert "usage: s3scanner [-h] [-o OUTFILE] [-c] [-r] [-d] [-l] buckets" in e.stdout.decode('utf-8')
```

**Pull request merged**
