### PR TITLE
Add argument to choose output style

### PR DESCRIPTION
**Pull request by klau5dev**
Hey, I add a argument. It's option for output filetype. And it doesn't affect test.
I think it would be better not to use logging to make output file.
Then we could add JSON or CSV output type.
Let me know your opinion, I think you may agree with that. https://github.com/sa7mon/S3Scanner/issues/82

### CODE REVIEW

**Comment by sa7mon** [comment]
Thanks for the PR. As you've referenced, I am in the process of doing a fairly substantial re-write of the tool that hopefully will be done soon™️. That said, I'm not sure this PR adds much value as-is. The user can choose the JSON output style, but it doesn't appear that they will actually get JSON output? 

I do like the idea of giving the user a choice between a verbose line with the checked permissions and a simple line with just the checked bucket.

**Comment by klau5dev** [comment]
Yes, this PR doesn't include writing output with JSON format.
I just want to talk about future implementation about this argument.. I wanted to add JSON option at first, but I thought it's hard to implement with logging library that using now.
If you agree with this, I'll write some code to use just file I/O and add JSON option, and PR again!

But you seem to re-writing this program. Is that OK to add some code on this code base?

**Comment by sa7mon** [comment]
Yes, I’m fine with updating this version before the re-write gets rolled out.

My only concern with the JSON option is to make sure the file output is a valid JSON document (I.e. if it contains an array of objects it needs to be surrounded by brackets). I couldn’t think of a good way to guarantee the output file has a man end bracket except to add a signal handler for when the user presses Ctrl+C.

**Comment by klau5dev** [comment]
How about this? 
1. Make output file and add `[ ]`.
2. Every time adding JSON format log (except first one), dump the new log object, and add `,` in front of the dumped log str, add `]` at the end of str.
3. Use file seek() and move at the location of `]`, and add the new log. Overwrite `]` that already exist with `,{JSON log data....}]`

I think this would be safe because deleting old `]` and adding new JSON log is atomic.
And for multithread, adding lock may help.

**Comment by klau5dev** [comment]
Hi, I added JSON output feature. Please take a look and merge if you like it!

**Comment by sa7mon** [comment]
The 2.0.0 release is nearing completion and should be ready to merge in the next week. If you'd like, I can merge this change and tag a 1.0.1 release before that, but just know that 2.0.0 will likely overwrite these changes.

**Comment by klau5dev** [comment]
Oh well then no need to merge.. I'm looking forward the 2.0.0! 🎉

**Comment by sa7mon** [comment]
Closing this due to the 2.0.0 release. Feel free to issue a new PR from the updated code.

**Pull request closed without merging**
